version: '3.8'
services:
  pg-auth:
    image: postgres:16
    container_name: pg-auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: authpass
    ports:
      - "5433:5432"
    volumes:
      - pg-auth-data:/var/lib/postgresql/data
volumes:
  pg-auth-data: 