// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	Email        string
	CreatedAt    time.Time
}
